<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Page;
use App\Models\Template;
use App\Models\Theme;

class PageSeeder extends Seeder
{
    public function run()
    {
        $temaAzul = Theme::where('slug', 'tema-azul')->first();
        $temaOscuro = Theme::where('slug', 'tema-oscuro')->first();

        $defaultTheme = $temaAzul ?? Theme::first();

        // Obtener plantillas por slug (usamos un mapa para acceder fácilmente)
        $templatesBySlug = [];
        $slugs = [
            'home-template',
            'shop-template',
            'product-detail-template',
            'cart-template',
            'checkout-template',
            'login-template',
            'register-template',
            'profile-template',
            'orders-template',
            'success-template',
            'link-bio-template',
            'policy-template',
            'basic-template',
        ];

        foreach ($slugs as $slug) {
            $templatesBySlug[$slug] = Template::where('slug', $slug)->first();
        }

        $basicTemplate = $templatesBySlug['basic-template'];

        $pages = [
            // Páginas para Company 1 (tema azul)
            [
                'title' => 'Inicio',
                'content' => '<p>Bienvenido a nuestra tienda.</p>',
                'page_type' => 'essential',
                'is_homepage' => true,
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['home-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['home-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Tienda',
                'content' => '<p>Explora nuestros productos.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['shop-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['shop-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Detalles del producto',
                'content' => '<p>Detalles del producto seleccionado.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['product-detail-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['product-detail-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Carrito de compras',
                'content' => '<p>Revisa tus productos.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['cart-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['cart-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Checkout',
                'content' => '<p>Completa tu compra.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['checkout-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['checkout-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Iniciar sesión',
                'content' => '<p>Accede a tu cuenta.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['login-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['login-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Registrarse',
                'content' => '<p>Crea una nueva cuenta.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['register-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['register-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Perfil de usuario',
                'content' => '<p>Administra tu perfil.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['profile-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['profile-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Pedidos',
                'content' => '<p>Historial de pedidos.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['orders-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['orders-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Orden exitosa',
                'content' => '<p>Tu orden ha sido procesada exitosamente.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['success-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['success-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Políticas de privacidad',
                'content' => '<p>Contenido de políticas de privacidad.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Términos de servicio',
                'content' => '<p>Contenido de términos de servicio.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Políticas de envío',
                'content' => '<p>Contenido de políticas de envío.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Política de devolución y reembolso',
                'content' => '<p>Contenido de devoluciones.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Información de contacto',
                'content' => '<p>Contenido de contacto.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 1,
            ],
            [
                'title' => 'Bio',
                'content' => '<p>Mis enlaces y redes.</p>',
                'page_type' => 'link_bio',
                'theme_id' => $temaAzul->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['link-bio-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['link-bio-template']?->layout_structure,
                'company_id' => 1,
            ],

            // Páginas para Company 2 (tema oscuro) - mismas asignaciones pero con otro tema
            [
                'title' => 'Inicio',
                'content' => '<p>Bienvenido a nuestra tienda.</p>',
                'page_type' => 'essential',
                'is_homepage' => true,
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['home-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['home-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Tienda',
                'content' => '<p>Explora nuestros productos.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['shop-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['shop-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Detalles del producto',
                'content' => '<p>Detalles del producto.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['product-detail-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['product-detail-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Carrito de compras',
                'content' => '<p>Revisa tu carrito.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['cart-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['cart-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Checkout',
                'content' => '<p>Finaliza tu compra.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['checkout-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['checkout-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Iniciar sesión',
                'content' => '<p>Accede a tu cuenta.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['login-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['login-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Registrarse',
                'content' => '<p>Crea una cuenta.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['register-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['register-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Perfil de usuario',
                'content' => '<p>Tu perfil.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['profile-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['profile-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Pedidos',
                'content' => '<p>Historial de pedidos.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['orders-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['orders-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Orden exitosa',
                'content' => '<p>Pedido confirmado.</p>',
                'page_type' => 'essential',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['success-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['success-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Bio',
                'content' => '<p>Mis enlaces.</p>',
                'page_type' => 'link_bio',
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['link-bio-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['link-bio-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Políticas de privacidad',
                'content' => '<p>Privacidad.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Términos de servicio',
                'content' => '<p>Términos.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Políticas de envío',
                'content' => '<p>Envío.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Política de devolución y reembolso',
                'content' => '<p>Devoluciones.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 2,
            ],
            [
                'title' => 'Información de contacto',
                'content' => '<p>Contacto.</p>',
                'page_type' => 'policy',
                'is_editable' => true,
                'theme_id' => $temaOscuro?->id ?? $defaultTheme->id,
                'uses_template' => true,
                'is_published' => true,
                'template_id' => $templatesBySlug['policy-template']?->id ?? $basicTemplate?->id,
                'layout' => $templatesBySlug['policy-template']?->layout_structure,
                'company_id' => 2,
            ],
        ];

        foreach ($pages as $page) {
            Page::updateOrCreate(
                [
                    'title' => $page['title'],
                    'company_id' => $page['company_id'],
                ],
                $page
            );
        }
    }
}